### ISSUE TITLE
LixoSafe crashes on Windows 11 with exception code c0000005

### ISSUE THREAD

**Issue by SetaCraft** [ArTicZera/GDI-Trojan.Win32.Lixo#1]
Hi, when I try running LixoSafe in my physical laptop with Windows 11, and also run along with Benzene Clean and Hydrogen Peaceful for battle (note: it crashes no matter if the other 2 are running or not), after running for a few moments, it crashes with exception code c0000005.

Update: ChorumeSafe and TranspireSafe also crash with same exception code as LixoSafe.

![Captura de pantalla 2023-12-10 153529](https://github.com/ArTicZera/GDI-Trojan.Win32.Lixo/assets/130748044/82ecea0d-35ce-48dc-b6b7-cbc29f2a6f94)

**Comment by ArTicZera** [comment]
I believe the reason for this problem is the HeapCreate function and Lixo's bytebeats (bad programming in general), so I have to take a deeper look at them, but this usually happens due to Windows version. 

Anyway, if you give me more information, like in which part of the execution this error occurs, I can take a better look and may fix it!

**Comment by SetaCraft** [comment]
I'll show you soon where it crashes (I will record it in video).
